### ISSUE TITLE
Gulp notify integration?

### ISSUE THREAD

**Issue by Lori2Lori** [callumacrae/gulp-w3cjs#10]
Is there any way to use [gulp notify](https://www.npmjs.com/package/gulp-notify) to display validation errors?

**Comment by callumacrae** [comment]
Yeah, use gulp-if and check for `file.w3cjs.success`.

**Comment by callumacrae** [comment]
Closing, not a bug.

**Comment by stephanoapiolaza** [comment]
this is the solution is 
```
.pipe(gulpIf("!<%= file.w3cjs.success %>",notify("There are errors with HTML5")))
```
The trouble is that always throw the notifications
