### ISSUE TITLE
Warning messages aren't intercepted

### ISSUE THREAD

**Issue by BroFox86** [callumacrae/gulp-w3cjs#21]
The plugin can't intercept the warning messages like this:

![2019-01-24 18 55 05](https://user-images.githubusercontent.com/23554264/51690486-d4e3bc80-2009-11e9-830e-c3f3ad44ad4d.png)

It works with errors only. How can i fix it?

**Comment by TheDancingCode** [comment]
You can pass `{ showInfo: true }` as an option to the plugin.

**Comment by BroFox86** [comment]
Thank you, it works!

**Comment by TheDancingCode** [comment]
Thank you for reporting. This option is now documented in the README.
