### ISSUE TITLE
Abort on Failure

### ISSUE THREAD

**Issue by dgateles** [callumacrae/gulp-w3cjs#23]
How to bypass failure without stop gulp process?

**Comment by TheDancingCode** [comment]
Do you mean that `w3cjs.reporter()` would not emit an error when validation errors are found?

**Comment by dgateles** [comment]
Emit but without stop gulp tasks, like a jshint

**Comment by TheDancingCode** [comment]
You can just omit the call to `w3cjs.reporter()`:
```js
gulp.task('w3cjs', function() {
  return gulp.src('src/*.html')
    .pipe(w3cjs());
});
```

**Comment by dgateles** [comment]
Great! Worked now!
