### ISSUE TITLE
Allow local validator

### ISSUE THREAD

**Issue by geedmo** [callumacrae/gulp-w3cjs#6]
Hi, would be good to have in options an uri param to set an url to a w3c local validator.
This should work right before call `w3cjs.validate` method

```js
if(options && options.uri) {
	w3cjs.setW3cCheckUrl(options.uri);
}
```

Then

```js
.pipe(w3cjs({uri: 'http://validator.localhost/check'}))
```

This helps a lot to work without worrying about the limits imposed by the online validator.

**Comment by callumacrae** [comment]
Sorry for the huge delay!

It's done here: https://github.com/callumacrae/gulp-w3cjs/commit/804fdab4e222bc3cefba4fc4824e1f34bd1329b1

I'll release it when we fix the deprecation errors, too.
